### ISSUE TITLE
Blue theme

### ISSUE THREAD

**Issue by deadcoder0904** [sallar/github-contributions-chart#10]
I use [Github Dark extension](https://github.com/StylishThemes/GitHub-Dark) which gives a nice blue theme. Would love that.

![screen shot 2018-05-03 at 2 22 28 am](https://user-images.githubusercontent.com/16436270/39548730-1d70b934-4e79-11e8-8af3-cd8052fb6c31.png)

**Comment by sallar** [comment]
This is available now ♥️

**Comment by deadcoder0904** [comment]
Wow that was fast
