### ISSUE TITLE
feat request: display number of git forks 

### ISSUE THREAD

**Issue by Abhijay007** [sallar/github-contributions-chart#105]
Display number of git forks on the site with along stars on the repo.

![image](https://user-images.githubusercontent.com/64387054/121713030-033e9580-cafa-11eb-9d84-62265fe13311.png)

we can place it on the right side of the git stars.

**Comment by sallar** [comment]
@Abhijay007 nobody's forking this...

**Comment by Abhijay007** [comment]
> @Abhijay007 nobody's forking this...

haha ok
