### ISSUE TITLE
Private contributions

### ISSUE THREAD

**Issue by roa-beep** [sallar/github-contributions-chart#116]
Hey all!

The app works great. However, it doesn't consider contributions in private repositories as part of the chart:( pls fix

**Comment by sallar** [comment]
@roa-beep thank you
you have to enable showing your private contributions on your chart for this to work:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/768052/162948466-0bd89a41-3654-4b87-8188-1ba212535382.png">

(this won't tell people which repos you have contributed to, just shows the green squares for them)
