### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by LitoMore** [sallar/github-contributions-chart#119]
Hi @sallar, seems your Vercel app is down. Could you give a check? Thanks!

<img width="413" alt="CleanShot 2022-09-26 at 23 45 41@2x" src="https://user-images.githubusercontent.com/8186898/192322004-99f0b227-cdc5-474a-9836-6a9760d8e2f9.png">

**Comment by sallar** [comment]
Hi. can you check again? seems to be working now

**Comment by smaeda-ks** [comment]
Although I can't seem to reproduce it either, if that's still happening to you, running a quick OpenSSL command from the same machine may provide more insights on this:

`openssl s_client -showcerts -servername github-contributions.vercel.app -connect cname.vercel-dns.com:443 2>&1`

bonus if you can also check (to make sure no one in the middle of the path is alternating your DNS query):
`dig +noall +answer github-contributions.vercel.app`

These output does not include any sensitive information so it's safe to paste it here.

**Comment by LitoMore** [comment]
Tried it on my phone, looks good now. Thanks!
