### ISSUE TITLE
Contribution count does not show up correctly

### ISSUE THREAD

**Issue by AneeshBose** [sallar/github-contributions-chart#127]
I tried to look at a contribution graph, and although the contributions are rendered correctly, the count shows up as 0. 
Please refer to below screenshot - 
![image](https://user-images.githubusercontent.com/15572618/210990824-d9541326-593f-49f7-8859-5717c9de0521.png)

**Comment by pietroppeter** [comment]
the contribution count appears correctly in the downloaded json

**Comment by LoaderB0T** [comment]
FYI: This seems to happen again, but for a different reason (client side), [I created an issue in the canvas repository](https://github.com/sallar/github-contributions-canvas/issues/65) and opened a PR to fix the issue
