### ISSUE TITLE
Make it easier to share

### ISSUE THREAD

**Issue by konojunya** [sallar/github-contributions-chart#13]
By placing the Twitter Share link you can create situations that are easy to share. 

Let's be able to share images and URL!

**Comment by Slaals** [comment]
We need to upload the image in the first place. Do you know of a service that allows to upload images for free?

I see an option which consists on using Twitter API and letting the user to upload the image in his/her Twitter account, then it's easy to tweet about it.

**Comment by ShivamSinghania** [comment]
And add a #hashtag on the website.

**Comment by abhishek-parmar1** [comment]
@Slaals you can also use a common platform to upload image (like imgur) and then use its link to share on any social platform.

**Comment by konojunya** [comment]
@abhishek-parmar1 I think that this plan is also good.

ex

Flicker: https://www.flickr.com/services/api/upload.api.html

imgur: https://api.imgur.com/endpoints/image/

**Comment by raxityo** [comment]
Twitter could also be used as an image hosting service without requiring OAuth. 😉 
Here's how it's done in [carbon.now.sh](carbon.now.sh):

1. Post a Tweet with your image from some predefined account. 
2. Find the media link from the resulting tweet. 
3. Attach this new link to your tweet composer. 

Reference:
- Tweet handler in carbon.now.sh: https://github.com/dawnlabs/carbon/blob/master/handlers/twitter.js
- Usage of this Tweet handler: https://github.com/dawnlabs/carbon/blob/89931eab59e2bf7bd594ba6451ff4030bccf4685/lib/api.js#L17-L27

**Comment by konojunya** [comment]
I will make a pull request!

**Comment by DanielRuf** [comment]
Could the clipboard / file API of the browser used here?

**Comment by konojunya** [comment]
@DanielRuf 
> Could the clipboard / file API of the browser used here?

I will try to implement such that base64 image data is requested to the server and the URL of the image is returned by Twitter API.
This is the same implementation method as https://github.com/dawnlabs/carbon.

**Comment by konojunya** [comment]
When implementing using Twitter's API, it seems that you have to make an account and tweet there.
So, create an account and implement it.

Reference: https://github.com/dawnlabs/carbon/blob/89931eab59e2bf7bd594ba6451ff4030bccf4685/handlers/twitter.js#L14
