### ISSUE TITLE
My profile can't be found

### ISSUE THREAD

**Issue by pseusys** [sallar/github-contributions-chart#130]
For example, my profile info should be available by [this link](https://github-contributions.vercel.app/api/v1/pseusys), but no info is found!  
The website shows `Could not find your profile` message. Is this because my profile is private? If so, is there a way of adding access to private profiles with e.g. an access token?

**Comment by sallar** [comment]
@pseusys yes this is because no data can be extracted from your profile. for now there's no way to access this type of accounts before I don't use the Github API to access your account, I crawl your public page.
