### ISSUE TITLE
[Feature] Just green squares - No title

### ISSUE THREAD

**Issue by Drjacky** [sallar/github-contributions-chart#139]
Could we have only this part somehow, no title, no username.
<img width="622" alt="Screenshot 2023-08-04 at 20 24 47" src="https://github.com/sallar/github-contributions-chart/assets/2296754/e577c507-acfe-405f-9071-0fe9bd512f3b">

**Comment by sallar** [comment]
@Drjacky the "core" module can be customized to do this, but it's currently out of scope for this project.
