### ISSUE TITLE
Website doesn't work: Could not find your profile

### ISSUE THREAD

**Issue by afbora** [sallar/github-contributions-chart#149]
https://github-contributions.vercel.app website doesn't work. I've tried my own and friends github account usernames but I'm getting always `Could not find your profile` error.

**Comment by LoaderB0T** [comment]
I have the same issue with the version I deployed locally. Have some GitHub APIs changed?

**Comment by sallar** [comment]
It seems like that Github has changed something on their profile page structure. Investigating.

**Comment by joshdance** [comment]
Same here not working currently.

**Comment by Codennnn** [comment]
@afbora @LoaderB0T @joshdance 

You could try [Green Wall](https://green-wall.leoku.dev), which provides a feature like this one that generates a contribution graph for you.
