### ISSUE TITLE
Username with "-" / Could not find your profile

### ISSUE THREAD

**Issue by ca-kraa** [sallar/github-contributions-chart#152]
why can't I use a username that has a strip symbol "-"? because my username uses the symbol

# If Use Symbol
![image](https://github.com/user-attachments/assets/132c6a0c-d21c-4b71-a48c-8232e68be711)

# if not Use Symbol
![image](https://github.com/user-attachments/assets/69b65009-9c8b-40a2-a295-1702bcf431fa)

**Comment by sierikov** [comment]
I can't reproduce this issue; usernames with a `-` are working as intended.

![Screenshot 2024-10-25 at 15 55 00](https://github.com/user-attachments/assets/9f92dc17-621e-42b6-9282-d2dbfb5f9ba9)

**Comment by ca-kraa** [comment]
Maybe this already fix it, Thanks for reply my issue
