### ISSUE TITLE
Missing years

### ISSUE THREAD

**Issue by jimmyff** [sallar/github-contributions-chart#154]
Hey, very neat app, however I just ran my chart and I'm missing entire years:
![image](https://github.com/user-attachments/assets/1865a9d7-3a68-4661-9559-17a96bb6be28)

![image](https://github.com/user-attachments/assets/fffb7dc2-d046-4e71-85e6-34d8c64c8c87)
![image](https://github.com/user-attachments/assets/8213f0be-fed1-4771-be40-8b6d78a111bc)

etc

**Comment by sierikov** [comment]
Just tried to reproduce this issue (Chrome + Firefox), but all years are filled. 
![Screenshot 2024-10-25 at 16 00 43](https://github.com/user-attachments/assets/d34acd82-f14a-4490-b5a7-3ce830340f3d)

If you still have an issue please provide more details.

**Comment by sallar** [comment]
Actually same thing happened to myself lol

![CleanShot 2024-10-25 at 18 43 51@2x](https://github.com/user-attachments/assets/0cb8e561-ec76-4b88-8837-31c255b687f9)

**Comment by sallar** [comment]
Should be ok now

![CleanShot 2024-10-25 at 18 58 57@2x](https://github.com/user-attachments/assets/1b1a401a-92fd-4211-bc1b-5168af62b9e7)
