### ISSUE TITLE
Isometric chart

### ISSUE THREAD

**Issue by edbizarro** [sallar/github-contributions-chart#16]
I use [Isometric Contributions](https://chrome.google.com/webstore/detail/isometric-contributions/mjoedlfflcchnleknnceiplgaeoegien) extension, which gives me a nice isometric pixel art chart.

Would be nice if you have something like these.

![edbizarro eduardo bizarro](https://user-images.githubusercontent.com/84926/39555812-54687f34-4e52-11e8-855d-17d587c51656.png)

**Comment by sallar** [comment]
@edbizarro this is a great idea.

**Comment by xudatui** [comment]
only can use the github?

**Comment by sallar** [comment]
It seems like that I'm always too busy for this. Im going to close this issue but in case someone is interested to implement it we can re-open and discuss it later.
