### ISSUE TITLE
New feature: Option to select for contribution on public, private or both repository 

### ISSUE THREAD

**Issue by gkunwar** [sallar/github-contributions-chart#18]
There should be a way to choose Private, Public and Both contributions while generating chart.

**Comment by sallar** [comment]
Thanks @gkunwar. This setting is controlled via your GitHub configurations and it's not something that we can control. We just read your profile.

![image](https://user-images.githubusercontent.com/768052/39580695-650bd17e-4ef2-11e8-8ac2-f1f6734595e0.png)

**Comment by gkunwar** [comment]
Thanks @sallar :)
