### ISSUE TITLE
Improvement: break into smaller components

### ISSUE THREAD

**Issue by helderburato** [sallar/github-contributions-chart#24]
@sallar what you think about? Create a smaller components to simplify add functionalities.

**Comment by sallar** [comment]
@helderburato what are your suggestions?

**Comment by helderburato** [comment]
First, make a `src/components` folder to all components, refactor `App.js` to break in minor stateless components, and last create `src/assets` folder to images, css and vendor files.

What you think?

**Comment by sallar** [comment]
@helderburato ah yes, I wanted to do that but the huge number of users prevented me to even think 😂 will do, thanks!

**Comment by helderburato** [comment]
If do you want help, just ask me 🤘

**Comment by sallar** [comment]
@helderburato well if you had any free time I'd appreciate the help :)

**Comment by helderburato** [comment]
The app structure:
```
src/*
src/assets/*
src/components/*
src/services/*
```
Is nice for start refactoring?

**Comment by sallar** [comment]
@helderburato looks good to me :)

**Comment by helderburato** [comment]
@sallar Updated app structure here #37, please review it. :)
