### ISSUE TITLE
Travis error?

### ISSUE THREAD

**Issue by eamanu** [sallar/github-contributions-chart#27]
Hello, 
I am seeing that the PRs are fail. Travis say: _The command "rake" exited with 1._
I don't know Travis, but it is configured correctly?

Regards

**Comment by DanielRuf** [comment]
Travis Ci is written in Ruby and uses Rake by default for Ruby projects.

It needs a .travis.yml with (different) settings to enable support for other projects.

See https://github.com/sallar/github-contributions-chart/pull/28

**Comment by sallar** [comment]
This is fixed by #28
