### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by WaleedAshraf** [sallar/github-contributions-chart#3]
Getting this error when I click generate:
<img width="540" alt="screen shot 2018-05-02 at 2 13 48 am" src="https://user-images.githubusercontent.com/8335457/39494120-9aa98bcc-4dae-11e8-9f56-98f71575c415.png">

I think it's this line: https://github.com/sallar/github-contributions-chart/blob/master/src/utils/draw.js#L87

**Comment by sallar** [comment]
This is fixed now. Thanks
