### ISSUE TITLE
test: plan and create unit tests

### ISSUE THREAD

**Issue by DanielRuf** [sallar/github-contributions-chart#34]
We should test the component(s), the result(s) and behavior.

Should we use jest / ava?

**Comment by sallar** [comment]
Jest is a good idea. Someone is splitting the components, maybe we can add tests to those?

**Comment by DanielRuf** [comment]
Relevant: https://github.com/sallar/github-contributions-chart/issues/24

**Comment by helderburato** [comment]
Hello @DanielRuf!
Today, I pushed here #37, please If you and @sallar could review that :)

**Comment by sallar** [comment]
I think this is out of date unfortunately. Im going to close it for now.
