### ISSUE TITLE
Add information for "total contributions"

### ISSUE THREAD

**Issue by mschwager** [sallar/github-contributions-chart#56]
Hey all,

Often when checking a user's contribution history it's interesting to know the total contribution count. We can sum the years by hand, but it'd be awesome if this was automated.

I'm envisioning something as simple as adding a line after "@user on GitHub" like "XXXX total contributions".

**Comment by sallar** [comment]
That's a great idea.

**Comment by adarsh-technocrat** [comment]
Hey 👋 @sallar @mschwager  can I work on this issue? it would be very interesting to show the total contribution count as describe by @mschwager !!

**Comment by amm98d** [comment]
@sallar I could take this up

**Comment by amm98d** [comment]
@sallar thanks, will submit a PR

**Comment by sallar** [comment]
Thanks @amm98d this is merged
