### ISSUE TITLE
Blank contribution graph

### ISSUE THREAD

**Issue by atymic** [sallar/github-contributions-chart#64]
The tool doesn't seem to be working for me. I've verified that the API request is successful, but nothing shows on the graph. The yearly contributions are correct.

![Screen Shot 2019-10-31 at 5 00 33 pm](https://user-images.githubusercontent.com/50683531/67922879-260b8700-fc00-11e9-86f3-372e38a6006b.png)

**Comment by sallar** [comment]
@atymic it seems like it works now:

![image](https://user-images.githubusercontent.com/768052/85958888-cab5b280-b9a1-11ea-9837-39922d5f023a.png)
