### ISSUE TITLE
How about Github Enterprise?

### ISSUE THREAD

**Issue by NishuGoel** [sallar/github-contributions-chart#66]
![image](https://user-images.githubusercontent.com/26349046/68534414-6c788880-035a-11ea-9ec5-eac1cc0f1cde.png)

**Comment by sallar** [comment]
@NishuGoel can you provide a little more information? The app does not know how to look for your profile if it's not hosted on Github.com

**Comment by sallar** [comment]
This feature is out of scope for this project, so I'm closing the issue.
