### ISSUE TITLE
GitHub Organizations

### ISSUE THREAD

**Issue by IndigoWizard** [sallar/github-contributions-chart#75]
It seems the app can't fetch organizations. It would be great to have it if possible.
![image](https://user-images.githubusercontent.com/43890965/79616618-c77e8a80-8105-11ea-8820-8d96b85bd410.png)

**Comment by sallar** [comment]
@IndigoWizard this app only supports what GitHub shows already on your profile and does not use the GitHub API. `github.com/USERNAME` is the format.

**Comment by iantearle** [comment]
Yeah, this would be really nice if it connected into private repos. I wonder how easy it would be to hook into the API?

**Comment by sallar** [comment]
This is out of scope for this project unfortunately.
