### ISSUE TITLE
It doesn't go through the whole history

### ISSUE THREAD

**Issue by vczh** [sallar/github-contributions-chart#76]
It misses my 2009 and 2010 record.

**Comment by sallar** [comment]
@vczh can your github page does not show 2009 and 2010.

![image](https://user-images.githubusercontent.com/768052/85958845-64c92b00-b9a1-11ea-8399-f8e8ee4a8ab0.png)

**Comment by vczh** [comment]
I checked my repos, it turns out that 2009 and 2010 are in one of my organization, but I set myself `Private` in `Peoples`. This could be the reason why I can see but the script cannot.
