### ISSUE TITLE
Did github change the API? The colors aren't being displayed in the chart anymore

### ISSUE THREAD

**Issue by sellingsolutions** [sallar/github-contributions-chart#78]
It seems to have stopped working just in the last couple of days?

<img width="672" alt="Screen Shot 2020-06-27 at 18 37 34" src="https://user-images.githubusercontent.com/1778201/85927277-4bdb4f80-b8a5-11ea-8345-b1dd4f2a6dd8.png">

This is the URL that I used: https://github-contributions.now.sh/

I have the same problem when running locally

**Comment by sallar** [comment]
@sellingsolutions seems like GitHub changed their UI a little bit which broke this app. Now fixed.

**Comment by Lateralus138** [comment]
I'm having this same exact issue as of `Novermber 6th, 2020`.

**Comment by sellingsolutions** [comment]
it's a bummer that they keep changing their UI

**Comment by sallar** [comment]
Oh damn. Im on it.

**Comment by devquestionz** [comment]
@sallar site is still not working :( 
https://github-contributions.now.sh/
