### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by GMartigny** [sallar/github-contributions-chart#89]
Hi,

When fetching data from Github, [the API](https://github-contributions.now.sh/api/v1/GMartigny) hit an error and fail. Not much details are send back, I only see a `Internal Server Error` with code 500.
From what I can see, it fails for any username.

**Comment by hokkqi** [comment]
I just tried to look up my username on it (both the frontend and the API you linked) and yeah, I also don't get any data back.
