### ISSUE TITLE
The live demo is not working

### ISSUE THREAD

**Issue by hasantezcan** [sallar/github-contributions-chart#94]
The live demo is not working 
![image](https://user-images.githubusercontent.com/32804505/108414376-36a0a000-723d-11eb-94ac-7bdb4f41dc56.png)

**Comment by iantearle** [comment]
Came here to write just the same thing.

**Comment by hasantezcan** [comment]
still not working 
![image](https://user-images.githubusercontent.com/32804505/108421212-e548de80-7245-11eb-923b-c6c5f8284e89.png)

**Comment by KevinZonda** [comment]
meet the same problem

**Comment by SuperThinking** [comment]
Have made the fix, will raise a PR in some time.

**Comment by sallar** [comment]
Sorry about this. Seems like the colors are off again

**Comment by SuperThinking** [comment]
Have created a PR that should fix this
https://github.com/sallar/github-contributions-chart/pull/95
