### ISSUE TITLE
How we can add the private contributions

### ISSUE THREAD

**Issue by hasantezcan** [sallar/github-contributions-chart#98]
I cant see my private contributions like on the GitHub profile page. How we can show them in the output image

**Comment by orozCoding** [comment]
Would love this.

**Comment by sallar** [comment]
you can control this yourself. on top of the contribution chart in github profile you can enable private contributions:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/768052/210256219-0717dc46-28cf-4efa-8cd3-01f9d5469f0b.png">
